### ISSUE TITLE
Mas una pregunta que un issue.

### ISSUE THREAD

**Issue by qmarquez** [MarluanEspiritusanto/ts-mapper#3]
Hola Marluan! Yo acá devuelta, te quería consultar, estoy viendo el curso de Nest que dejaste al final del de Node y ahí llegué a esta biblioteca que subiste a npm.

Consulta, el método createMap no sería mejor que esté como protected? para que solo se puedan crear mappers desde las clases que extiendan de él en vez de desde cualquier lado.

**Comment by qmarquez** [comment]
Por otro lado, estuve probando y quizá es un poco mas complejo, pero destination no se puede instanciar por defecto como un objeto para no tener que estar escribiendo por todos lados que vamos a mapear a un nuevo objeto?

**Comment by marluanespiritusanto** [comment]
Saludos @qmarquez, este proyecto fue creado por la necesidad que me surgió al intentar parsear objetos a dtos y vice versa en TypeScript. Al momento de crearlo ignoré por completo las opciones que Nest.js brinda para solucionar este problema. Una vez documentado, opté por usar la opción sugerida por la comunidad y decidí detener el desarrollo. Más adelante en el curso vas a poder ver cómo implemento [class-validator](https://www.npmjs.com/package/class-validator) y [class-transformer](https://www.npmjs.com/package/class-transformer) para garantizar una mejor integración.

De todas formas, el proyecto quedará abierto a PRs para mejorar pero, de mi parte por el momento no recibirá mantenimiento.
